import { api } from "@/api/endpoints";
import { useToast } from "@/app/useToast";
import { Button } from "@/components/ui/Button";
import { Card } from "@/components/ui/Card";
import { controlClass, labelClass } from "@/components/ui/styles";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { PageHeader, QueryState } from "./shared";
import { formatDate } from "./table-utils";

export default function ConfigPage() {
  const query = useQuery({ queryKey: ["admin", "config"], queryFn: api.currentGlobalConfig }); const history = useQuery({ queryKey: ["admin", "config", "history"], queryFn: api.globalConfigHistory }); const [draft, setDraft] = useState(""); const [policyDraft, setPolicyDraft] = useState(""); const [reason, setReason] = useState(""); const [diff, setDiff] = useState<Array<{ key: string; before: unknown; after: unknown }> | null>(null); const { toast } = useToast(); const client = useQueryClient();
  useEffect(() => { if (query.data) { setDraft(JSON.stringify(query.data.values, null, 2)); setPolicyDraft(JSON.stringify(query.data.policies, null, 2)); } }, [query.data]);
  const publish = useMutation({ mutationFn: async () => { const patch = JSON.parse(draft) as Record<string, unknown>; const policies = JSON.parse(policyDraft) as Record<string, string>; const result = await api.diffGlobalConfig(patch); if (diff === null) { setDiff(result.changes); throw new Error("Review the generated diff, then publish again to confirm"); } return api.publishGlobalConfig(patch, policies, reason, query.data?.version ?? 0); }, onSuccess: (data) => { client.invalidateQueries({ queryKey: ["admin"] }); setReason(""); setDiff(null); toast(`Configuration version ${data.version} published`); }, onError: (error) => toast(error instanceof Error ? error.message : "Configuration publication failed") });
  const rollback = useMutation({ mutationFn: ({ version, reason }: { version: number; reason: string }) => api.rollbackGlobalConfig(version, reason), onSuccess: () => { client.invalidateQueries({ queryKey: ["admin"] }); toast("Configuration rollback published as a new version"); } });
  function requestRollback(version: number) { const rollbackReason = window.prompt(`Reason to roll back to version ${version}:`); if (rollbackReason?.trim()) rollback.mutate({ version, reason: rollbackReason.trim() }); }
  return <><PageHeader title="Global configuration" description="Validate and publish versioned defaults applied across the product." actions={<span className="text-sm text-muted">Active version {query.data?.version ?? 0}</span>} /><QueryState loading={query.isLoading} error={query.error}>{query.data && <div className="grid gap-4 xl:grid-cols-[minmax(0,1fr)_20rem]"><div className="grid gap-4"><Card><label className={labelClass}>Configuration JSON<textarea className={`${controlClass} min-h-[32rem] font-mono text-xs`} value={draft} onChange={(e) => { setDraft(e.target.value); setDiff(null); }} spellCheck={false} /></label></Card><Card><label className={labelClass}>Override policies JSON<textarea className={`${controlClass} min-h-48 font-mono text-xs`} value={policyDraft} onChange={(e) => { setPolicyDraft(e.target.value); setDiff(null); }} spellCheck={false} /></label><p className="mt-2 text-xs text-muted">Use user_overridable or locked for registry paths.</p></Card></div><div className="grid content-start gap-4"><Card><h2 className="font-bold">Publish changes</h2><p className="mt-1 text-sm text-muted">Publication is validated, persisted, versioned, and written to the audit log.</p><label className={`${labelClass} mt-4`}>Required reason<textarea className={`${controlClass} min-h-28`} value={reason} onChange={(e) => setReason(e.target.value)} /></label>{diff && <div className="mt-4 rounded-xl border border-border p-3 text-xs"><strong>{diff.length} changed settings</strong>{diff.slice(0, 8).map((item) => <p key={item.key} className="mt-1 break-all">{item.key}: {JSON.stringify(item.before)} → {JSON.stringify(item.after)}</p>)}</div>}<Button className="mt-4" disabled={publish.isPending || reason.trim().length < 3} onClick={() => publish.mutate()}>{publish.isPending ? "Working..." : diff === null ? "Validate and review diff" : "Confirm and publish"}</Button></Card><Card><h2 className="font-bold">Version history</h2><div className="mt-3 grid gap-2">{history.data?.items.map((item) => <div key={item.version} className="rounded-xl border border-border p-3 text-sm"><strong>Version {item.version}</strong><p className="text-xs text-muted">{item.reason || "No reason"} · {formatDate(item.created_at)}</p>{item.version !== query.data?.version && <button className="mt-2 text-xs font-semibold underline" onClick={() => requestRollback(item.version)}>Roll back to this version</button>}</div>)}</div></Card></div></div>}</QueryState></>;
}